apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  workspaces:
    - name: source
  params:
    - name: image-name
      type: string
  steps:
    - name: build-go-image
      image:  quay.io/buildah/stable:v1.17.0
      workingdir: $(workspaces.source.path)
      command: ["/bin/bash"]
      args: ["-c","buildah bud -t $(params.image-name) ./Dockerfile ;"]
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
    - name: push-to-dockerhub
      image: quay.io/buildah/stable:v1.17.0
      workingdir: $(workspaces.source.path)
      command: ["/bin/bash"]
      args: ["-c","buildah push --creds $USERNAME:$PASSWORD localhost/$(params.image-name)  docker://$USERNAME/$(params.image-name) ;"]
      env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: docker-creds
            key: USERNAME
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: docker-creds
            key: PASSWORD
      volumeMounts:
      - name: varlibcontainers
        mountPath: /var/lib/containers
      securityContext:
        privileged: true
  volumes:
    - name: varlibcontainers
      emptyDir: {}