apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  workspaces:
    - name: source
  steps:
    - name: initialize-db
      image: lachlanevenson/k8s-kubectl
      workingdir: $(workspaces.source.path)
      command: ["/bin/sh"]
      args: ["-c","ls ci/; kubectl create secret generic mysqldb-user-creds --from-file ./config.txt"]
    - name: check
      image:  lachlanevenson/k8s-kubectl
      workingdir: $(workspaces.source.path)
      command: ["/bin/sh"]
      args: ["-c"," kubectl apply -f ./k8/dbDeployment.yaml"]
      