apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  selector:
    app: mysqldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: 3306-3306
  type: ClusterIP
status: 
  loadBalancer: {}